window.esdocSearchIndex = [
  [
    "@data-structure-algebra/singly-linked-list/src/node.js~node",
    "function/index.html#static-function-Node",
    "<span>Node</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/Node.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/_insertafter.js~_insertafter",
    "function/index.html#static-function-_insertAfter",
    "<span>_insertAfter</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/_insertAfter.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/_islast.js~_islast",
    "function/index.html#static-function-_isLast",
    "<span>_isLast</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/_isLast.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/_iter.js~_iter",
    "function/index.html#static-function-_iter",
    "<span>_iter</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/_iter.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/_iter_fast.js~_iter_fast",
    "function/index.html#static-function-_iter_fast",
    "<span>_iter_fast</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/_iter_fast.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/_last.js~_last",
    "function/index.html#static-function-_last",
    "<span>_last</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/_last.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/_len.js~_len",
    "function/index.html#static-function-_len",
    "<span>_len</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/_len.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/_pop.js~_pop",
    "function/index.html#static-function-_pop",
    "<span>_pop</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/_pop.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/_setnext.js~_setnext",
    "function/index.html#static-function-_setNext",
    "<span>_setNext</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/_setNext.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/_setvalue.js~_setvalue",
    "function/index.html#static-function-_setValue",
    "<span>_setValue</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/_setValue.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/_shift.js~_shift",
    "function/index.html#static-function-_shift",
    "<span>_shift</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/_shift.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/concat.js~concat",
    "function/index.html#static-function-concat",
    "<span>concat</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/concat.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/empty.js~empty",
    "function/index.html#static-function-empty",
    "<span>empty</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/empty.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/from.js~from",
    "function/index.html#static-function-from",
    "<span>from</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/from.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/insertafter.js~insertafter",
    "function/index.html#static-function-insertAfter",
    "<span>insertAfter</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/insertAfter.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/isempty.js~isempty",
    "function/index.html#static-function-isEmpty",
    "<span>isEmpty</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/isEmpty.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/islast.js~islast",
    "function/index.html#static-function-isLast",
    "<span>isLast</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/isLast.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/islist.js~islist",
    "function/index.html#static-function-isList",
    "<span>isList</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/isList.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/isnonempty.js~isnonempty",
    "function/index.html#static-function-isNonEmpty",
    "<span>isNonEmpty</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/isNonEmpty.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/iter.js~iter",
    "function/index.html#static-function-iter",
    "<span>iter</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/iter.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/last.js~last",
    "function/index.html#static-function-last",
    "<span>last</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/last.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/len.js~len",
    "function/index.html#static-function-len",
    "<span>len</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/len.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/pop.js~pop",
    "function/index.html#static-function-pop",
    "<span>pop</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/pop.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/push.js~push",
    "function/index.html#static-function-push",
    "<span>push</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/push.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/setvalue.js~setvalue",
    "function/index.html#static-function-setValue",
    "<span>setValue</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/setValue.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/shift.js~shift",
    "function/index.html#static-function-shift",
    "<span>shift</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/shift.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/single.js~single",
    "function/index.html#static-function-single",
    "<span>single</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/single.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/unshift.js~unshift",
    "function/index.html#static-function-unshift",
    "<span>unshift</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/unshift.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/_value.js~value",
    "function/index.html#static-function-value",
    "<span>value</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/_value.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/value.js~value",
    "function/index.html#static-function-value",
    "<span>value</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/value.js</span>",
    "function"
  ],
  [
    "@data-structure-algebra/singly-linked-list/src/values.js~values",
    "function/index.html#static-function-values",
    "<span>values</span> <span class=\"search-result-import-path\">@data-structure-algebra/singly-linked-list/src/values.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/node.js",
    "file/src/Node.js.html",
    "src/Node.js",
    "file"
  ],
  [
    "src/_insertafter.js",
    "file/src/_insertAfter.js.html",
    "src/_insertAfter.js",
    "file"
  ],
  [
    "src/_islast.js",
    "file/src/_isLast.js.html",
    "src/_isLast.js",
    "file"
  ],
  [
    "src/_iter.js",
    "file/src/_iter.js.html",
    "src/_iter.js",
    "file"
  ],
  [
    "src/_iter_fast.js",
    "file/src/_iter_fast.js.html",
    "src/_iter_fast.js",
    "file"
  ],
  [
    "src/_last.js",
    "file/src/_last.js.html",
    "src/_last.js",
    "file"
  ],
  [
    "src/_len.js",
    "file/src/_len.js.html",
    "src/_len.js",
    "file"
  ],
  [
    "src/_pop.js",
    "file/src/_pop.js.html",
    "src/_pop.js",
    "file"
  ],
  [
    "src/_setnext.js",
    "file/src/_setNext.js.html",
    "src/_setNext.js",
    "file"
  ],
  [
    "src/_setvalue.js",
    "file/src/_setValue.js.html",
    "src/_setValue.js",
    "file"
  ],
  [
    "src/_shift.js",
    "file/src/_shift.js.html",
    "src/_shift.js",
    "file"
  ],
  [
    "src/_value.js",
    "file/src/_value.js.html",
    "src/_value.js",
    "file"
  ],
  [
    "src/concat.js",
    "file/src/concat.js.html",
    "src/concat.js",
    "file"
  ],
  [
    "src/empty.js",
    "file/src/empty.js.html",
    "src/empty.js",
    "file"
  ],
  [
    "src/from.js",
    "file/src/from.js.html",
    "src/from.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/insertafter.js",
    "file/src/insertAfter.js.html",
    "src/insertAfter.js",
    "file"
  ],
  [
    "src/isempty.js",
    "file/src/isEmpty.js.html",
    "src/isEmpty.js",
    "file"
  ],
  [
    "src/islast.js",
    "file/src/isLast.js.html",
    "src/isLast.js",
    "file"
  ],
  [
    "src/islist.js",
    "file/src/isList.js.html",
    "src/isList.js",
    "file"
  ],
  [
    "src/isnonempty.js",
    "file/src/isNonEmpty.js.html",
    "src/isNonEmpty.js",
    "file"
  ],
  [
    "src/iter.js",
    "file/src/iter.js.html",
    "src/iter.js",
    "file"
  ],
  [
    "src/last.js",
    "file/src/last.js.html",
    "src/last.js",
    "file"
  ],
  [
    "src/len.js",
    "file/src/len.js.html",
    "src/len.js",
    "file"
  ],
  [
    "src/pop.js",
    "file/src/pop.js.html",
    "src/pop.js",
    "file"
  ],
  [
    "src/push.js",
    "file/src/push.js.html",
    "src/push.js",
    "file"
  ],
  [
    "src/setvalue.js",
    "file/src/setValue.js.html",
    "src/setValue.js",
    "file"
  ],
  [
    "src/shift.js",
    "file/src/shift.js.html",
    "src/shift.js",
    "file"
  ],
  [
    "src/single.js",
    "file/src/single.js.html",
    "src/single.js",
    "file"
  ],
  [
    "src/unshift.js",
    "file/src/unshift.js.html",
    "src/unshift.js",
    "file"
  ],
  [
    "src/value.js",
    "file/src/value.js.html",
    "src/value.js",
    "file"
  ],
  [
    "src/values.js",
    "file/src/values.js.html",
    "src/values.js",
    "file"
  ]
]